#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

if [ "$1" == "exclude" ]; then
    echo "\nGenerating HTML report of the code coverage of Xcode project, excludeing third-party libraries\n"
    EXCLUDE="true"
else
    echo "\nGenerating HTML report of the code coverage of Xcode project, including third-party libraries\n"
    EXCLUDE="false"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

remove_old_report()
{
    echo "Remove old report..."
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    echo "Enter ${BUILT_PRODUCTS_DIR} ..."
    cd "${BUILT_PRODUCTS_DIR}"
    mkdir lcov
    cd lcov
}

remove_source()
{

    for file in $*; do
        rm "${OBJECT_FILE_DIR_normal}/${CURRENT_ARCH}/$file.gcda"
    done
}

gather_coverage()
{
    echo "\nGather covarege ..."
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    echo "\nExclude third-party libraries ..."
    LCOV --remove ${LCOV_INFO} "Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    #LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}

    if [ $EXCLUDE = "true" ]; then
        for i in `ls -d $PRGROOT/*/ | egrep -wv "Supervisor Dashboard|SupervisorAPI-Bindings"`
        do
            pattern=`echo $i | awk -F $PRGROOT/ '{ print $2 }'`
            echo "Removing $i" 
            LCOV --remove ${LCOV_INFO} "$pattern*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
        done 
    fi
}

generate_report()
{
   echo "\nGenerate report..."
   "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
   open index.html
   echo "\n####     A browser window is opened. Now you can see the code coverage!    ####\n"
   echo "Full HTML code coverage report is located at $BUILT_PRODUCTS_DIR/lcov."

}

remove_old_report || exit
enter_lcov_dir || exit
#remove_source AppDelegate SupervisorAPIConnector
gather_coverage || exit
exclude_data || exit
generate_report || exit
