#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

remove_old_report()
{
    echo "Remove old report..."
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    echo "Enter ${BUILT_PRODUCTS_DIR} ..."
    cd "${BUILT_PRODUCTS_DIR}"
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    echo "\nGather covarege ..."
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    echo "\nExclude third-party libraries ..."
    LCOV --remove ${LCOV_INFO} "Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_report()
{
   echo "\nGenerate report..."
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
   echo "\n####     A browser window is opened. Now you can see thhe code coverage!    ####"
}

remove_old_report || exit
enter_lcov_dir || exit
gather_coverage || exit
exclude_data || exit
generate_report || exit
